### ISSUE TITLE
Feature -SOCIAL MEDIA BOX

### ISSUE THREAD

**Issue by pope410211** [sjoyal/TIY-Github#4]
@sjoyal 
* Grab your mac!
  * [x] create a social media container using a `<div>`.
  * [x] give it a `class` of your choice
    * using `HTML`
      * [x] style a button using a `ul` and `li` 
        * [ ] give them `class` names.
      * [x] close those tags
      * [x] create additional `ul` & `li`
      * [x] put place holder text ex:
        * [ ] 1k  2 6
        * _There is a way to place text underneath such as followers, following, and starred, not sure how at the moment_
         * [ ] for the below text -i.e. followers, following, and starred- follow above steps to create another `<div>`.
     * Using `css`
       * [x] Style the button
         * [x] Color & Size

![mobile-social-info-div-sjoyal-pt1](https://cloud.githubusercontent.com/assets/12172658/8021610/200a8e80-0c74-11e5-8522-534441486299.png)
![mobile-social-media-sjoyal-pt2](https://cloud.githubusercontent.com/assets/12172658/8021611/200edce2-0c74-11e5-89f3-26abf5907eec.png)

**Comment by sjoyal** [comment]
#3

**Comment by sjoyal** [comment]
#11
